apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector
  namespace: linkedin-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::160198385987:role/linkedin-adot-collector-role
