apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector
  namespace: linkedin-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/linkedin-adot-collector-role