apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-service
  namespace: linkedin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile-service
  template:
    metadata:
      labels:
        app: userprofile-service
    spec:
      containers:
        - name: userprofile-service
          image: docker.io/shubhratripathi16/userprofile-service:main-42-10a8f6ee19bc
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: linkedin-config
            - secretRef:
                name: linkedin-secrets
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(RDS_HOST):$(RDS_PORT)/$(USERPROFILE_DB_NAME)
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_PASSWORD