apiVersion: v1
kind: Service
metadata:
  name: jenkins-public
  namespace: jenkins
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: agent
      port: 50000
      targetPort: agent
      protocol: TCP
