apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: linkedin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: shubhratripathi16/search-service:latest
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: linkedin-config
            - secretRef:
                name: linkedin-secrets