apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: linkedin-prod
  labels:
    app: search-service
spec:
  selector:
    app: search-service
  ports:
    - name: http
      port: 8086
      targetPort: http
  type: ClusterIP
