apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkedin-frontend
  namespace: linkedin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkedin-frontend
  template:
    metadata:
      labels:
        app: linkedin-frontend
    spec:
      containers:
        - name: linkedin-frontend
          image: docker.io/shubhratripathi16/linkedin-frontend:main-42-10a8f6ee19bc
          ports:
            - containerPort: 3000