apiVersion: v1
kind: Service
metadata:
  name: linkedin-frontend
  namespace: linkedin-prod
spec:
  type: LoadBalancer
  selector:
    app: linkedin-frontend
  ports:
    - port: 3000
      targetPort: 3000