apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
  namespace: linkedin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
    spec:
      containers:
        - name: subscription-service
          image: shubhratripathi16/subscription-service:latest
          ports:
            - containerPort: 8094
          envFrom:
            - configMapRef:
                name: linkedin-config
            - secretRef:
                name: linkedin-secrets
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(RDS_HOST):$(RDS_PORT)/$(SUBSCRIPTION_DB_NAME)
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_PASSWORD