apiVersion: v1
kind: Service
metadata:
  name: connections-service
  namespace: linkedin-prod
spec:
  selector:
    app: connections-service
  ports:
    - name: http
      port: 8093
      targetPort: http
  type: ClusterIP
