apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - start
            - --http-enabled=true
            - --hostname-strict=false
          ports:
            - containerPort: 8080
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: {{ .Values.dbSecret.usernameKey }}
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: {{ .Values.dbSecret.passwordKey }}
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: {{ .Values.admin.usernameSecretKey }}
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: {{ .Values.admin.passwordSecretKey }}
