apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: linkedin-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: shubhratripathi16/api-gateway:latest
          ports:
            - containerPort: 8085