apiVersion: v1
kind: Service
metadata:
  name: prometheus-public
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: kube-prometheus-stack-prometheus
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: kube-prometheus-stack-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http-web
      protocol: TCP
