apiVersion: v1
kind: ConfigMap
metadata:
  name: linkedin-config
  namespace: linkedin-prod
data:
  SPRING_PROFILES_ACTIVE: prod
  RDS_HOST: linkedin-postgres.cj8ekcimav3i.eu-west-2.rds.amazonaws.com
  RDS_PORT: "5432"
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_SSL_ENABLED: "false"

  FEED_DB_NAME: feeddb
  POST_DB_NAME: postdb
  USERPROFILE_DB_NAME: userprofiledb
  SEARCH_DB_NAME: searchdb
  CONNECTION_DB_NAME: connectiondb
  JOBPOSTING_DB_NAME: jobpostingdb
  NOTIFICATION_DB_NAME: notificationdb
  MESSAGING_DB_NAME: messagingdb
  SUBSCRIPTION_DB_NAME: subscriptiondb


  MSK_BOOTSTRAP_SERVERS: b-1.linkedinmsk.vnj8l2.c3.kafka.eu-west-2.amazonaws.com:9092,b-2.linkedinmsk.vnj8l2.c3.kafka.eu-west-2.amazonaws.com:9092
  OPENSEARCH_URL: https://vpc-linkedin-search-5jrtdntrpho4npixlj4qurnpym.eu-west-2.es.amazonaws.com

  FEED_SERVICE_URI: http://feed-service:8087
  POST_SERVICE_URI: http://post-service:8088
  SEARCH_SERVICE_URI: http://search-service:8086
  USERPROFILE_SERVICE_URI: http://userprofile-service:8083

  API_GATEWAY_PORT: "8085"
  FEED_SERVICE_PORT: "8087"
  POST_SERVICE_PORT: "8088"
  SEARCH_SERVICE_PORT: "8086"
  USERPROFILE_SERVICE_PORT: "8083"
  JOBPOSTING_SERVICE_PORT: "8091"
  NOTIFICATION_SERVICE_PORT: "8090"

  KEYCLOAK_DB_HOST: linkedin-postgres.cj8ekcimav3i.eu-west-2.rds.amazonaws.com
  KEYCLOAK_DB_PORT: "5432"
  KEYCLOAK_DB_NAME: keycloakdb

  KEYCLOAK_INTERNAL_URL: http://keycloak:8080



  KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/linkedin-app/protocol/openid-connect/certs

  KEYCLOAK_EXTERNAL_URL: http://a9099f2319da740c3b1c3e37813205aa-704837357.eu-west-2.elb.amazonaws.com:8080
  KEYCLOAK_ISSUER_URI: http://a9099f2319da740c3b1c3e37813205aa-704837357.eu-west-2.elb.amazonaws.com:8080/realms/linkedin-app
  REACT_APP_KEYCLOAK_URL: http://a9099f2319da740c3b1c3e37813205aa-704837357.eu-west-2.elb.amazonaws.com:8080

  REACT_APP_API_BASE_URL: http://ac2511ef9149847f0ae9ed56e0f05ba3-876930999.eu-west-2.elb.amazonaws.com:8085

  SPRING_KAFKA_BOOTSTRAP_SERVERS: b-1.linkedinmsk.vnj8l2.c3.kafka.eu-west-2.amazonaws.com:9092,b-2.linkedinmsk.vnj8l2.c3.kafka.eu-west-2.amazonaws.com:9092
  ELASTICSEARCH_URI: vpc-linkedin-search-5jrtdntrpho4npixlj4qurnpym.eu-west-2.es.amazonaws.com


  REACT_APP_KEYCLOAK_REALM: linkedin-app
  REACT_APP_KEYCLOAK_CLIENT_ID: linkedin-frontend

  APP_GATEWAY_SECURITY_ALLOWED_ORIGINS_0: "http://ade5840dc3ec0494cba966d84b187f2c-490133502.eu-west-2.elb.amazonaws.com:3000"
  APP_GATEWAY_SECURITY_ALLOWED_TOKEN_CLIENTS_0: "linkedin-frontend"
  APP_GATEWAY_SECURITY_ALLOWED_TOKEN_CLIENTS_1: "api-gateway"

  SPRING_KAFKA_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  SCHEMA_REGISTRY_URL: http://schema-registry:8081



