apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - media-service-account.yaml
  - configmap.yaml
  - secret.yaml
  - redis/deplyment.yaml
  - redis/service.yaml
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - feed-service/deployment.yaml
  - feed-service/service.yaml
  - post-service/deployment.yaml
  - post-service/service.yaml
  - search-service/deployment.yaml
  - search-service/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - userprofile-service/deployment.yaml
  - userprofile-service/service.yaml
  - jobposting-service/deployment.yaml
  - jobposting-service/service.yaml
  - notification-service/deployment.yaml
  - notification-service/service.yaml
  - keycloak/deployment.yaml
  - keycloak/service.yaml
  - keycloak/bootstrap-configmap.yaml
  - keycloak/bootstrap-cronjob.yaml
  - connections-service/deployment.yaml
  - connections-service/service.yaml
  - schema-registry/deployment.yaml
  - schema-registry/service.yaml
  - kafka-topics/job.yaml
  - monitoring/spring-boot-servicemonitor.yaml
  - monitoring/prometheus-rules.yaml
  - monitoring/grafana-linkedin-full-stack-dashboard.yaml
  - monitoring/grafana-public-service.yaml
  - monitoring/prometheus-public-service.yaml
  - monitoring/loki-configmap.yaml
  - monitoring/loki-deployment.yaml
  - monitoring/loki-service.yaml
  - monitoring/promtail-rbac.yaml
  - monitoring/promtail-configmap.yaml
  - monitoring/promtail-daemonset.yaml
  - monitoring/grafana-loki-datasource.yaml
  - jenkins/namespace.yaml
  - jenkins/admin-init-configmap.yaml
  - jenkins/deployment.yaml
  - jenkins/service.yaml
  - adot-collector/service-account.yaml
  - adot-collector/configmap.yaml
  - adot-collector/deployment.yaml
  - adot-collector/service.yaml
  - cloudwatch-logs/namespace.yaml
  - cloudwatch-logs/service-account.yaml
  - cloudwatch-logs/rbac.yaml
  - cloudwatch-logs/configmap.yaml
  - cloudwatch-logs/daemonset.yaml
