apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml

  - api-gateway/deployment.yaml
  - api-gateway/service.yaml

  - feed-service/deployment.yaml
  - feed-service/service.yaml

  - post-service/deployment.yaml
  - post-service/service.yaml

  - search-service/deployment.yaml
  - search-service/service.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml

  - userprofile-service/deployment.yaml
  - userprofile-service/service.yaml

  - jobposting-service/deployment.yaml
  - jobposting-service/service.yaml

  - notification-service/deployment.yaml
  - notification-service/service.yaml

  - keycloak/deployment.yaml
  - keycloak/service.yaml

  - connection-service/deployment.yaml
  - connection-service/service.yaml
