apiVersion: v1
kind: ServiceAccount
metadata:
  name: media-service-account
  namespace: linkedin-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::160198385987:role/linkedin-clone-dev-media-service
