apiVersion: v1
kind: Secret
metadata:
  name: linkedin-secrets
  namespace: linkedin-prod
type: Opaque
stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: LinkedIn123
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: linkedin123
  KEYCLOAK_DB_USERNAME: postgres
  KEYCLOAK_DB_PASSWORD: LinkedIn123
  STRIPE_SECRET_KEY: sk_test_REPLACE_ME
  STRIPE_WEBHOOK_SECRET: whsec_REPLACE_ME
