apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
  namespace: linkedin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
        - name: feed-service
          image: docker.io/shubhratripathi16/feed-service:main-51-4588455f13ef
          ports:
            - containerPort: 8087

          envFrom:
            - configMapRef:
                name: linkedin-config
            - secretRef:
                name: linkedin-secrets

          env:
            - name: POSTGRES_URL
              value: jdbc:postgresql://$(RDS_HOST):$(RDS_PORT)/$(FEED_DB_NAME)
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: linkedin-config
                  key: MSK_BOOTSTRAP_SERVERS