apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/shubhra-tripathi/linkedin-clone-gitops.git
    targetRevision: main
    path: charts/keycloak

  destination:
    server: https://kubernetes.default.svc
    namespace: linkedin-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true