apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: linkedin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: docker.io/shubhratripathi16/notification-service:main-43-ed8f34707228
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: linkedin-config
            - secretRef:
                name: linkedin-secrets
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(RDS_HOST):$(RDS_PORT)/$(NOTIFICATION_DB_NAME)
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_PASSWORD