apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: linkedin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service


          image: docker.io/shubhratripathi16/notification-service:main-95-fb4f12b20073

          ports:
            - name: http
              containerPort: 8090
          envFrom:
            - configMapRef:
                name: linkedin-config
            - secretRef:
                name: linkedin-secrets
          env:
            - name: SERVER_PORT
              value: "8090"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/opentelemetry/opentelemetry-javaagent.jar"
            - name: OTEL_SERVICE_NAME
              value: "notification-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://adot-collector:4318"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_TRACES_SAMPLER
              value: "traceidratio"
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "0.01"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(RDS_HOST):$(RDS_PORT)/$(NOTIFICATION_DB_NAME)
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
