apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobposting-service
  namespace: linkedin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobposting-service
  template:
    metadata:
      labels:
        app: jobposting-service
    spec:
      containers:
        - name: jobposting-service
          image: docker.io/shubhratripathi16/jobposting-service:main-41-a7c64b3af051
          ports:
            - containerPort: 8091
          envFrom:
            - configMapRef:
                name: linkedin-config
            - secretRef:
                name: linkedin-secrets
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(RDS_HOST):$(RDS_PORT)/$(JOBPOSTING_DB_NAME)
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_PASSWORD