apiVersion: v1
kind: Service
metadata:
  name: jobposting-service
  namespace: linkedin-prod
spec:
  selector:
    app: jobposting-service
  ports:
    - name: http
      port: 8091
      targetPort: http
  type: ClusterIP
