apiVersion: v1
kind: Secret
metadata:
  name: linkedin-secrets
  namespace: linkedin-prod
type: Opaque
stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: LinkedIn123
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: linkedin123
  KEYCLOAK_DB_USERNAME: postgres
  KEYCLOAK_DB_PASSWORD: LinkedIn123