apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: linkedin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: docker.io/shubhratripathi16/api-gateway:main-51-4588455f13ef
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: linkedin-config
            - secretRef:
                name: linkedin-secrets