apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: linkedin-prod
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8085
      targetPort: http
