apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: linkedin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.7.1
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://b-1.linkedinmsk.vnj8l2.c3.kafka.eu-west-2.amazonaws.com:9092,PLAINTEXT://b-2.linkedinmsk.vnj8l2.c3.kafka.eu-west-2.amazonaws.com:9092
            - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
              value: PLAINTEXT