apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: linkedin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      serviceAccountName: media-service-account
      containers:
        - name: post-service

          image: docker.io/shubhratripathi16/post-service:main-80-abb524b920ae

          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: linkedin-config
            - secretRef:
                name: linkedin-secrets
          env:
            - name: POSTGRES_URL
              value: jdbc:postgresql://$(RDS_HOST):$(RDS_PORT)/$(POST_DB_NAME)
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: linkedin-config
                  key: MSK_BOOTSTRAP_SERVERS
            - name: AWS_REGION
              value: eu-west-2

            - name: AWS_S3_BUCKET
              value: linkedin-clone-dev-uploads-160198385987
