apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: linkedin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      serviceAccountName: media-service-account
      containers:
        - name: post-service

          image: docker.io/shubhratripathi16/post-service:main-83-6a8354d34e90

          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: linkedin-config
            - secretRef:
                name: linkedin-secrets
          env:
            - name: POSTGRES_URL
              value: jdbc:postgresql://$(RDS_HOST):$(RDS_PORT)/$(POST_DB_NAME)
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/opentelemetry/opentelemetry-javaagent.jar"
            - name: OTEL_SERVICE_NAME
              value: "post-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://adot-collector:4318"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_TRACES_SAMPLER
              value: "traceidratio"
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "0.01"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkedin-secrets
                  key: DB_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: linkedin-config
                  key: MSK_BOOTSTRAP_SERVERS
            - name: AWS_REGION
              value: eu-west-2

            - name: AWS_S3_BUCKET
              value: linkedin-clone-dev-uploads-160198385987
