apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: linkedin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: shubhratripathi16/post-service:latest
          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: linkedin-config
            - secretRef:
                name: linkedin-secrets