apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: linkedin-prod
  labels:
    app: post-service
spec:
  selector:
    app: post-service
  ports:
    - name: http
      port: 8088
      targetPort: http
  type: ClusterIP
